FROM ultralytics/ultralytics:8.4.80-cpu

WORKDIR /app

RUN pip install --no-cache-dir          \
    "imagezmq==1.2.0"                   \
    "dill==0.4.1"

COPY . .

CMD ["python3", "-u", "detect.py"]
