FROM ultralytics/ultralytics:8.3.253

WORKDIR /app

RUN pip install --no-cache-dir          \
    "imagezmq==1.2.0"                   \
    "dill==0.3.9"

COPY . .

CMD ["python3", "-u", "detect.py"]
