services:

  neural-np-easyocr:
    container_name: neural-np-easyocr
    image: neural-np-easyocr
    build:
      context: ./source_code/np-easyocr
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    networks:
      - external
    restart: unless-stopped



  neural-objects:
    container_name: neural-objects
    image: neural-yolov7
    build:
      context: ./source_code/yolov7
      dockerfile: Dockerfile
    environment:
      DETECT_WEIGHTS: ./neural_networks/yolov7.pt
      # DETECT_WEIGHTS: ./neural_networks/yolov7-e6e.pt
      # DETECT_WEIGHTS: ./neural_networks/yolov7-tiny.pt
      DETECT_RECREATE_TRACE_MODEL: "False"
      DETECT_TRACED_MODEL_PATH: ./neural_networks/tracedmodel_OUT.pt
      DETECT_IMGSZ: "320"
      DETECT_CONF_THRES: "0.5"
      DETECT_IOU_THRES: "0.45"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./yolov7-objects:/app/neural_networks
    networks:
      - external
    restart: unless-stopped



  neural-np-location:
    container_name: neural-np-location
    image: neural-yolov7
    build:
      context: ./source_code/yolov7
      dockerfile: Dockerfile
    environment:
      DETECT_WEIGHTS: ./neural_networks/LP_detect_yolov7_500img.pt
      DETECT_RECREATE_TRACE_MODEL: "False"
      DETECT_TRACED_MODEL_PATH: ./neural_networks/tracedmodel_IN.pt
      DETECT_IMGSZ: "1024"
      DETECT_CONF_THRES: "0.40"
      DETECT_IOU_THRES: "0.45"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: all
              capabilities: [gpu]
    volumes:
      - ./yolov7-np-location:/app/neural_networks
    networks:
      - external
    restart: unless-stopped


networks:
  external:
    name: external
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
