services:


  # Using YOLO11 from Ultralytics to apply OCR on the numberplates
  neural-np-ocr:
    container_name: neural-np-ocr
    image: neural-ultralytics
    build:
      context: ./source_code/ultralytics-yolo
      dockerfile: Dockerfile.cpu
    environment:
      DETECT_WEIGHTS: ./neural_networks/yolo11n-np-ocr.pt
      DETECT_IMGSZ: "320"
      DETECT_CONF_THRES: "0.30"
      DETECT_IOU_THRES: "0.7"

    # # Uncomment using NVIDIA GPU
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: all
    #           capabilities: [gpu]

    volumes:
      - ./yolo-np-ocr:/app/neural_networks
    networks:
      - external
    restart: unless-stopped




  # Using YOLO11 from Ultralytics
  neural-objects:
    container_name: neural-objects
    image: neural-ultralytics
    build:
      context: ./source_code/ultralytics-yolo
      dockerfile: Dockerfile.cpu
    environment:
      DETECT_WEIGHTS: yolo11l.pt
      DETECT_IMGSZ: "320"
      DETECT_CONF_THRES: "0.40"

    # # Uncomment using NVIDIA GPU
    # deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]

    networks:
      - external
    restart: unless-stopped




  # Using YOLO11 from Ultralytics
  neural-np-location:
    container_name: neural-np-location
    image: neural-ultralytics
    build:
      context: ./source_code/ultralytics-yolo
      dockerfile: Dockerfile.cpu
    environment:
      DETECT_WEIGHTS: ./neural_networks/yolo11n-np-v3.pt
      DETECT_IMGSZ: "640"
      DETECT_CONF_THRES: "0.20"
      DETECT_IOU_THRES: "0.05"

    # # Uncomment using NVIDIA GPU
    # deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]

    volumes:
      - ./yolo-np:/app/neural_networks
    networks:
      - external
    restart: unless-stopped




  # Using YOLOv10 from Ultralytics to apply OCR on the numberplates
  neural-np-ocr-best:
    container_name: neural-np-ocr-best
    image: neural-ultralytics
    build:
      context: ./source_code/ultralytics-yolo
      dockerfile: Dockerfile.cpu
    environment:
      DETECT_WEIGHTS: ./neural_networks/yolov10x-np-ocr.pt
      DETECT_IMGSZ: "320"
      DETECT_CONF_THRES: "0.45"
      DETECT_IOU_THRES: "0.7"

    # # Uncomment using NVIDIA GPU
    # deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]

    volumes:
      - ./yolo-np-ocr:/app/neural_networks
    networks:
      - external
    restart: unless-stopped




networks:
  external:
    name: external
    external: true
    ipam:
      config:
        - subnet: 172.18.0.0/24
          gateway: 172.18.0.1
